spring:
  application:
    name: demo-containerized-app
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        transaction: DEBUG
        security: DEBUG
      hibernate:
        SQL: DEBUG

server:
  port: 8080
